<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8FHCG9S\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8FHCG9S/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8FHCG9S.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8FHCG9S\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8FHCG9S\App_KernelDevDebugContainer([
    'container.build_hash' => '8FHCG9S',
    'container.build_id' => 'faed7876',
    'container.build_time' => 1625228571,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8FHCG9S');
